In [2]:
from warnings import simplefilter

import tensorflow as tf

# Always a good idea for tensorflow, imo
simplefilter(action='ignore', category=FutureWarning)

print(tf.__version__)


2.11.0


## Tensors

In [6]:
# Creating Resource Variables
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# These tensors have a shape of 0 (rank 0), which means they're a "scalar".
print(string)
print(number)
print(floating)


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [7]:
# One list, one array, one dimension; a vector.
rank1_tensor = tf.Variable(["Test"], tf.string)
rank1_tensor

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>

In [8]:
# Lists inside of a list, a matrix:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
rank2_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>

In [10]:
# How to get the rank
tf.rank(rank1_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### Tip!

If it says: `Can't convert non-rectangular Python sequence to tensor`, it means you screwed up the number of elements somewhere.

## The Shape of Tensors

In [13]:
# TENSOR SHAPE
rank1_tensor.shape # Because it's a rank 1, we only get 1 number

TensorShape([1])

In [14]:
rank2_tensor.shape

TensorShape([2, 2])

## Changing Shape

The number of elements of a tensor is the product of the sizes of all its shapes.

In [15]:
tensor1 = tf.ones([1, 2, 3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor1.shape


TensorShape([1, 2, 3])

In [16]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])  # reshape existing data to shape [2,3,1]
tensor2.shape


TensorShape([2, 3, 1])

In [18]:
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
# this will reshape the tensor to [3,2]
tensor3.shape

TensorShape([3, 2])

In [19]:
# The number of elements in the reshaped tensor MUST match the number in the original

print("tensor1:", tensor1)
print("\ntensor2:", tensor2)
print("\ntensor3:", tensor3)
# Notice the changes in shape


tensor1: tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

tensor2: tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)

tensor3: tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## You can skip this if you feel comfortable

`tensor1` (1, 2, 3) has 1 interior list, and 2 lists inside of that list, and 3 elements in each of those lists.

```json
[
  [
    [1, 1, 1],
    [1, 1, 1]
  ]
]
```

`tensor2` (2, 3, 1) we have 2 lists, inside of those we have 3 lists, and 1 element inside each of those lists.

```json
[
  [
    [1], [1], [1]
  ],
  [
    [1], [1], [1]
  ]
]
```

`tensor3` with the `-1` means: let the computer figure it out.

3 * 2 = 6

(3, 2) means we have 3 lists in there, with 2 things in each list.

```json
[
  [1, 1],
  [1, 1],
  [1, 1]
]
```

## TensorFlow tensor to ndarray

Keep in mind that the NumPy ndarray and the TensorFlow tensor share the same underlying data, so changes to one will affect the other.

In [25]:
import tensorflow as tf
import numpy as np

# create a TensorFlow tensor
x = tf.constant([[1, 2], [3, 4]])

# convert the tensor to a NumPy ndarray
x_np = x.numpy()

# print the NumPy ndarray
print("\narray:\n", x_np)
print("\ndtype:", x_np.dtype)
print("\nshape:", x_np.shape)



array:
 [[1 2]
 [3 4]]

dtype: int32

shape: (2, 2)


In [35]:
# So instead of dealing with all this bs, you could just add `.numpy().shape`
tf.constant([[1, 2], [3, 4]]).numpy().shape

(2, 2)

Of course this is before I found out that you can just do `tensor.shape` <span style="font-size:27px;">😋</span>

### Create a tensor full of ones

In [28]:
tf.ones([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

## Slicing Tensors

[Tensor Slicing](https://www.tensorflow.org/guide/tensor_slicing)

The slice operator can be used on tensors to select specific axes or elements.

When working on ML applications such as object detection and NLP, it is sometimes necessary to work with sub-sections (slices) of tensors.

Example:

In [32]:
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])

tf.slice(
    t1,
    begin=[1],
    size=[3]
)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [34]:
# Creating a 2D tensor
matrix = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
]

tensor = tf.Variable(matrix, dtype=tf.int32)
print("\nrank:", tf.rank(tensor))
print("\nshape:", tensor.shape)



rank: tf.Tensor(2, shape=(), dtype=int32)

shape: (4, 5)


In [36]:
# Let's select some different rows and columns from our tensor

three = tensor[0, 2]  # selects the 3rd element from the 1st row
print("\n3rd element:", three)



3rd element: tf.Tensor(3, shape=(), dtype=int32)


In [37]:
row1 = tensor[0]  # selects the first row
print("\n1st row:", row1)



1st row: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [38]:
column1 = tensor[:, 0]  # selects the first column
print("\n1st column:", column1)



1st column: tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [39]:
row_2_and_4 = tensor[1::2]  # selects second and fourth row (heh?)
print("\nrows 2 and 4:", row_2_and_4)



rows 2 and 4: tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


In [40]:
column_1_in_row_2_and_3 = tensor[1:3, 0]
print("\n1st column, rows 2 and 3:", column_1_in_row_2_and_3)



1st column, rows 2 and 3: tf.Tensor([ 6 11], shape=(2,), dtype=int32)


## Sources

https://www.tensorflow.org/guide/tensor